### ISSUE TITLE
NPC для Кронта

### ISSUE THREAD

**Issue by m1kc** [uonline/universe#24]
> (22:31:07) m1kc: (22:30:59) m1kc: > Шоц, лекарь
> Кажется, в Кронте завелись евреи. Я не удивлюсь, если окажется, что он ещё и дантист.
> (22:31:32) АндРЕЙ: это тебя смущает) Имена - первое, что в голову приходит
> (22:33:00) m1kc: А чо фамилий ни у кого нет?
> (22:33:17) АндРЕЙ: эм... Обычно их нет)
> (22:33:25) m1kc: Раса ни у кого не указана.
> (22:34:48) m1kc: Там вообще кто - люди, орки, whatever?
> (22:35:10) АндРЕЙ: орки
> (22:35:29) m1kc: И больше никого?
> (22:36:15) АндРЕЙ: да, пожалуй
### tasks
- [ ] Мне не нравится расовый еврей Шац;
- [ ] Следует всё-таки подумать над наличием у орков фамилий (родовых имён?) или объяснить, какого хуя их нет;
- [ ] Следует указать у всех расу и, возможно, чуть разнообразить расовый состав.
