### ISSUE TITLE
Roadmap a.k.a. долгая дорога до релиза

### ISSUE THREAD

**Issue by m1kc** [uonline/universe#74]
> Faceless:
- [ ] боевая система должна быть реализована {:page_facing_up: #3, :page_facing_up: [all.md](https://github.com/uonline/universe/blob/master/%D0%94%D0%B8%D0%B7%D0%B0%D0%B9%D0%BD-%D0%B4%D0%BE%D0%BA%D1%83%D0%BC%D0%B5%D0%BD%D1%82/all.md)}
- [ ] локации:
  - [ ] учитывая, что РБ у нас будут не сразу - просто города с малоуровневыми монстрами (да, и они должны быть)
  - [ ] провинциальные местноси и глухие места (а-ля лес, чащи всякие, берега и прочая херня, не принадлежащая кому-либо)
- [ ] потом нам необходимо раскидать предметы, разместить НПС. под "предметы" имеется в виду не только оружие/доспехи/лечилки/камни, но и сырье. какое я проебал в файлике, все не напишу никак заново, бля...
- [ ] потом надо набросать еще локаций типа шахт и рудников, на которых персонажи будут въебывать в поте лица.
- [x] потом нам надо внести характеристики для персонажей
- [ ] урегулировать способности персонажа.
- [ ] решить какие классы реализуем пока сейчас, а какие дадим в обновлениях (вместе с кораблями -корабли - на обновление, я помню).
- [ ] систему навыков доделать.
- [ ] Ачивка для участвовавших в бете;
- [ ] квесты должны быть реализованы. хотя бы несколько.
- [ ] крафт допилить. 
- [ ] расписать какое оружие куда отнесется. я про систему распределения как в Диабло. там оружие было "редкое", "стандартное" и прочее-прочее-прочее. например, если оно у нас "легендарное" 0 нельзя его выбить из РБ. никак. из РБ можно выбить "редкое".
- [ ] нам бы распределить локации: PvP/не-PvP по отдельности или весь мир
- [ ] ну, необходимо еще ввести Инструменты. для профессий. кузнецу - кузнечный молот, рудокопу - кирку, травнику - нож, портному... бля, что портному? набор игл, думаю, логичен.
- [ ] нам необходимо урегулировать каково количество профессий будет доступно для параллельного вкачивания. все - так все. но что-то как-то неинтересно, если игрок будет уметь все и сразу.
- [ ] чуть позже - заняться той самой "Доской", возможно, игрок будет видеть сообщения вроде "наступили сумерки" и прочее.
- [ ] чат и внутриигровая почта

> m1kc: Добавь к этому списку внутренние нужды движка. Вот тебе и объём работ до релиза.

**Comment by FaceLess1** [comment]
это все написал я? хм, да я "молоток") иногда просто не верится, что я -- автор.

**Comment by m1kc** [comment]
Ну вот, из 19 задач готова аж целая одна. Хорошо идём.

**Comment by FaceLess1** [comment]
"доска" может подождать.
внутриигровая почта может подождать. или предпочтительнее, чтобы она была? особенно чат может подождать.
поскольку беты еще нет -- ачивка тоже может подождать.

**Comment by FaceLess1** [comment]
пишу о статусе-кво задач:
1. локации -- в процессе; существует редактор локаций, обсуждение на 90% касается только меня и Лени
2. РБ не начинались; нужен ли отдельный редактор для РБ?! обсуждение на 80% касается меня и Лени 
3. распределение мест работы не начиналось; отдельный редактор(?), обсуждение всей командой
4. распределение предметов не начиналось; новый редактор(?), на общее обсуждение
5. характеристики персонажей -- исполнено
6. способности персонажа не урегулированы из-за 7; работа для меня и Лени на 90%
7. способности классов не проработаны; работа всей командой
8. квесты отсутствуют; общее обсуждение
9. крафт не реализован; общее обсуждение
10. оружие не до конца распределено; работаю я и Леня
11. чат и почта, не реализовывалось никак.

**Comment by FaceLess1** [comment]
"боевая система должна быть реализована" -- в процессе, необходима магия и скиллы персонажей
 "локации" -- в процессе, необходимо распределение расовых городов и нейтральных территорий на карте:
 "учитывая, что РБ у нас будут не сразу - просто города с малоуровневыми монстрами (да, и они должны быть)" -- не начиналось.
 "провинциальные местности и глухие места (а-ля лес, чащи всякие, берега и прочая херня, не принадлежащая кому-либо)" -- не начиналось
 "раскидать предметы, разместить НПС. под "предметы" имеется в виду не только оружие/доспехи/лечилки/камни, но и сырье" -- не начиналось
 "потом надо набросать еще локаций типа шахт и рудников, на которых персонажи будут въебывать в поте лица." -- обсуждалось, но не реализовывалось.
 "потом нам надо внести характеристики для персонажей" -- готово
 "урегулировать способности персонажа по классам" -- не обсуждалось
 "решить какие классы реализуем пока сейчас, а какие дадим в обновлениях (вместе с кораблями -корабли - на обновление, я помню)" -- не начиналось.
 "систему навыков доделать" -- не начиналось
 "Ачивка для участвовавших в бете" -- не начиналось
 "квесты должны быть реализованы. хотя бы несколько" -- не реализовано, обсуждалось
 "крафт допилить" -- не реализовано
 "расписать какое оружие куда отнесется. я про систему распределения как в Диабло. там оружие было "редкое", "стандартное" и прочее-прочее-прочее. например, если оно у нас "легендарное" 0 нельзя его выбить из РБ. никак. из РБ можно выбить "редкое" " -- не обсуждалось
 "нам бы распределить локации: PvP/не-PvP по отдельности или весь мир" -- не обсуждалось
 "ну, необходимо еще ввести Инструменты. для профессий. кузнецу - кузнечный молот, рудокопу - кирку, травнику - нож, портному... бля, что портному? набор игл, думаю, логичен." -- в процессе реализации
 "нам необходимо урегулировать каково количество профессий будет доступно для параллельного вкачивания. все - так все. но что-то как-то неинтересно, если игрок будет уметь все и сразу" -- не обсуждалось.
 "чуть позже - заняться той самой "Доской", возможно, игрок будет видеть сообщения вроде "наступили сумерки" и прочее" -- не начиналось.
 "чат и внутриигровая почта" -- не начиналось.
